config/routes.rb
Neon::Application.routes.draw do

  get "inventory/index"
  get "inventory/import"
  resources :timelines, :av_devices, :printers,:idevices, :devices  do
    collection { post :import }
  end
  
  devise_for :users,  :controllers => {:sessions => "sessions"},:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}  #devise_for :users

  root 'welcome#index'

  
  get "/graph", to: "charts#graph",  as: "graph"
  get "/pie", to: "charts#pie",  as: "pie"
  get "/bar", to: "charts#bar",  as: "bar"
  get "/upload", to: "inventory#index", as: "upload_inventory" 
  post "/inventory/import", to: "inventory#import", as: "import_inventory"

end

app/models/av_device.rb
class AvDevice < ActiveRecord::Base
   attr_accessible :brand, :device, :location, :model, :asset_tag, :serial_number, :status, :value, :lease, :lease_term, :owner_or_teacher, :notes
   def self.import(file)
     spreadsheet = Import::Uploader.open_spreadsheet(file)
     spreadsheet.default_sheet = "AV - Interactive"
     Processheet.process_spreadsheet(spreadsheet, self)
   end
  
  def self.process_result(row)  
    if colmn = ['serial_number','asset_tag'].find {|col| row[col] }
    # if row["serial_number"].present? || row["asset_tag"].present? || row["location"].present?
      # device = send("find_by_#{colmn}", row[colmn]) || new
      device = where({"#{colmn}"=> row[colmn]}).first || new
      device.attributes = row.to_hash.slice(*accessible_attributes)
      device.save!
    else
      where(row).first_or_create  
    end
  end
  
   def self.search(search)
    if search
      where('device LIKE ? or brand LIKE ? or status LIKE ? or owner_or_teacher LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/av_devices_controller.rb
class AvDevicesController < ApplicationController
  before_action :set_av_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /av_devices
  # GET /av_devices.json
  def index
    @av_devices = AvDevice.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /av_devices/1
  # GET /av_devices/1.json
  def show
  end
  
  def import
    AvDevice.import(params[:file])
    redirect_to av_devices_path, notice: 'AV devices were successfully created.'
  end
  
  # GET /av_devices/new
  def new
    @av_device = AvDevice.new
  end

  # GET /av_devices/1/edit
  def edit
  end

  # POST /av_devices
  # POST /av_devices.json
  def create
    @av_device = AvDevice.new(av_device_params)

    respond_to do |format|
      if @av_device.save
        format.html { redirect_to @av_device, notice: 'Av device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @av_device }
      else
        format.html { render action: 'new' }
        format.json { render json: @av_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /av_devices/1
  # PATCH/PUT /av_devices/1.json
  def update
    respond_to do |format|
      if @av_device.update(av_device_params)
        format.html { redirect_to @av_device, notice: 'Av device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @av_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /av_devices/1
  # DELETE /av_devices/1.json
  def destroy
    @av_device.destroy
    respond_to do |format|
      format.html { redirect_to av_devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_av_device
      @av_device = AvDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def av_device_params
      params.require(:av_device).permit(:status, :asset_tag, :device, :location, :brand, :model, :serial_number, :value, :lease, :lease_term, :owner_or_teacher, :notes)
    end
    
    def sort_column
      AvDevice.column_names.include?(params[:sort]) ? params[:sort] : "brand"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/av_devices_helper.rb
module AvDevicesHelper
end

app/views/av_devices/_avdevices.haml
- model_class = AvDevice
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= sortable "status"
      %th= model_class.human_attribute_name(:asset_tag)
      %th= sortable "device"
      %th= model_class.human_attribute_name(:location)
      %th= sortable "brand"
      %th= model_class.human_attribute_name(:model)
      %th= model_class.human_attribute_name(:serial_number)
      %th= model_class.human_attribute_name(:value)
      %th= model_class.human_attribute_name(:lease)
      %th= model_class.human_attribute_name(:lease_term)
      %th= sortable "owner_or_teacher"
      %th= model_class.human_attribute_name(:notes)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @av_devices.each do |av_device|
      %tr
        %td= link_to av_device.id, av_device_path(av_device)
        %td= av_device.status
        %td= av_device.asset_tag
        %td= av_device.device
        %td= av_device.location
        %td= av_device.brand
        %td= av_device.model
        %td= av_device.serial_number
        %td= av_device.value
        %td= av_device.lease
        %td= av_device.lease_term
        %td= av_device.owner_or_teacher
        %td= av_device.notes
        %td=l av_device.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_av_device_path(av_device), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), av_device_path(av_device), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
    .pagination{align: 'right'}
      = will_paginate @av_devices, renderer: BootstrapPagination::Rails
= link_to t('.new', :default => t("helpers.links.new")), new_av_device_path, :class => 'btn btn-primary'

app/views/av_devices/_form.haml
= form_for @av_device, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :asset_tag, :class => 'control-label'
    .controls
      = f.text_field :asset_tag, :class => 'text_field'
  .control-group
    = f.label :device, :class => 'control-label'
    .controls
      = f.text_field :device, :class => 'text_field'
  .control-group
    = f.label :location, :class => 'control-label'
    .controls
      = f.text_field :location, :class => 'text_field'
  .control-group
    = f.label :brand, :class => 'control-label'
    .controls
      = f.text_field :brand, :class => 'text_field'
  .control-group
    = f.label :model, :class => 'control-label'
    .controls
      = f.text_field :model, :class => 'text_field'
  .control-group
    = f.label :serial_number, :class => 'control-label'
    .controls
      = f.text_field :serial_number, :class => 'text_field'
  .control-group
    = f.label :value, :class => 'control-label'
    .controls
      = f.text_field :value, :class => 'text_field'
  .control-group
    = f.label :lease, :class => 'control-label'
    .controls
      = f.text_field :lease, :class => 'text_field'
  .control-group
    = f.label :lease_term, :class => 'control-label'
    .controls
      = f.text_field :lease_term, :class => 'text_field'
  .control-group
    = f.label :owner_or_teacher, :class => 'control-label'
    .controls
      = f.text_field :owner_or_teacher, :class => 'text_field'
  .control-group
    = f.label :notes, :class => 'control-label'
    .controls
      = f.text_field :notes, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), av_devices_path, :class => 'btn'

app/views/av_devices/edit.haml
- model_class = AvDevice
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/av_devices/index.haml
- model_class = AvDevice
.page-header
  %h1=t '.title', :default => "Audio / Visual Interactive Devices"
  %h3=t '.sub_title',:default => "SmartBoards, Document Cameras, Projectors, Sound Equipment, Overhead, etc…" 
= render partial: '/shared/search', locals:{partial: 'avdevices', path: av_devices_path}  
= render '/shared/import', file_name: "AVDevices.xlsx", import_path: import_av_devices_path

app/views/av_devices/index.js.haml
$("#devices").html("<%= escape_javascript(render("avdevices")) %>");

app/views/av_devices/new.haml
- model_class = AvDevice
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/av_devices/show.haml
- model_class = AvDevice
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @av_device.status
%p
  %strong= model_class.human_attribute_name(:asset_tag) + ':'
  %br
  = @av_device.asset_tag
%p
  %strong= model_class.human_attribute_name(:device) + ':'
  %br
  = @av_device.device
%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @av_device.location
%p
  %strong= model_class.human_attribute_name(:brand) + ':'
  %br
  = @av_device.brand
%p
  %strong= model_class.human_attribute_name(:model) + ':'
  %br
  = @av_device.model
%p
  %strong= model_class.human_attribute_name(:serial_number) + ':'
  %br
  = @av_device.serial_number
%p
  %strong= model_class.human_attribute_name(:value) + ':'
  %br
  = @av_device.value
%p
  %strong= model_class.human_attribute_name(:lease) + ':'
  %br
  = @av_device.lease
%p
  %strong= model_class.human_attribute_name(:lease_term) + ':'
  %br
  = @av_device.lease_term
%p
  %strong= model_class.human_attribute_name(:owner_or_teacher) + ':'
  %br
  = @av_device.owner_or_teacher
%p
  %strong= model_class.human_attribute_name(:notes) + ':'
  %br
  = @av_device.notes

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), av_devices_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_av_device_path(@av_device), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), av_device_path(@av_device), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'