config/routes.rb
Neon::Application.routes.draw do

  get "inventory/index"
  get "inventory/import"
  resources :timelines, :av_devices, :printers,:idevices, :devices  do
    collection { post :import }
  end
  
  devise_for :users,  :controllers => {:sessions => "sessions"},:path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}  #devise_for :users

  root 'welcome#index'

  
  get "/graph", to: "charts#graph",  as: "graph"
  get "/pie", to: "charts#pie",  as: "pie"
  get "/bar", to: "charts#bar",  as: "bar"
  get "/upload", to: "inventory#index", as: "upload_inventory" 
  post "/inventory/import", to: "inventory#import", as: "import_inventory"

end

app/models/idevice.rb
class Idevice < ActiveRecord::Base
 attr_accessible :name, :device_type, :model_number, :hd_capacity, :serial_number, :asset_tag
   def self.import(file)
     spreadsheet = Import::Uploader.open_spreadsheet(file)
     spreadsheet.default_sheet = "iDevices"
     Processheet.process_spreadsheet(spreadsheet, self)
   end

  def self.process_result(row)
    device = find_by_serial_number(row["serial_number"]) || find_by_asset_tag(row["asset_tag"]) || new
    device.attributes = row.to_hash.slice(*accessible_attributes)
    device.save!
  end
  
  def self.search(search)
    if search
      where('name LIKE ? or device_type LIKE ? or model_number LIKE ? or serial_number LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/idevices_controller.rb
class IdevicesController < ApplicationController
  before_action :set_idevice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /idevices
  # GET /idevices.json
  def index
    # @idevices = Idevice.paginate(page: params[:page], per_page: 10)
    @idevices = Idevice.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /idevices/1
  # GET /idevices/1.json
  def show
  end
  
  def import
    Idevice.import(params[:file])
    redirect_to idevices_path, notice: 'iDevices were successfully created.'
  end

  # GET /idevices/new
  def new
    @idevice = Idevice.new
  end

  # GET /idevices/1/edit
  def edit
  end

  # POST /idevices
  # POST /idevices.json
  def create
    @idevice = Idevice.new(idevice_params)

    respond_to do |format|
      if @idevice.save
        format.html { redirect_to @idevice, notice: 'Idevice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @idevice }
      else
        format.html { render action: 'new' }
        format.json { render json: @idevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idevices/1
  # PATCH/PUT /idevices/1.json
  def update
    respond_to do |format|
      if @idevice.update(idevice_params)
        format.html { redirect_to @idevice, notice: 'Idevice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @idevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idevices/1
  # DELETE /idevices/1.json
  def destroy
    @idevice.destroy
    respond_to do |format|
      format.html { redirect_to idevices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_idevice
    @idevice = Idevice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def idevice_params
    params.require(:idevice).permit(:device_type, :model_number, :capacity_hd, :serial_number, :asset_tag, :name)
  end
  def sort_column
    Idevice.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/idevices_helper.rb
module IdevicesHelper
end

app/views/idevices/_form.haml
= form_for @idevice, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :device_type, :class => 'control-label'
    .controls
      = f.text_field :device_type, :class => 'text_field'
  .control-group
    = f.label :model_number, :class => 'control-label'
    .controls
      = f.text_field :model_number, :class => 'text_field'
  .control-group
    = f.label :capacity_hd, :class => 'control-label'
    .controls
      = f.text_field :capacity_hd, :class => 'text_field'
  .control-group
    = f.label :serial_number, :class => 'control-label'
    .controls
      = f.text_field :serial_number, :class => 'text_field'
  .control-group
    = f.label :asset_tag, :class => 'control-label'
    .controls
      = f.text_field :asset_tag, :class => 'text_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), idevices_path, :class => 'btn'

app/views/idevices/_idevices.haml
- model_class = Idevice
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= sortable "device_type"
      %th= sortable "model_number"
      %th= model_class.human_attribute_name(:capacity_hd)
      %th= sortable "serial_number"
      %th= model_class.human_attribute_name(:asset_tag)
      %th= sortable "name"
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @idevices.each do |idevice|
      %tr
        %td= link_to idevice.id, idevice_path(idevice)
        %td= idevice.device_type
        %td= idevice.model_number
        %td= idevice.capacity_hd
        %td= idevice.serial_number
        %td= idevice.asset_tag
        %td= idevice.name
        %td=l idevice.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_idevice_path(idevice), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), idevice_path(idevice), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
    .pagination{align: 'right'}
      = will_paginate @idevices, renderer: BootstrapPagination::Rails
= link_to t('.new', :default => t("helpers.links.new")), new_idevice_path, :class => 'btn btn-primary'

app/views/idevices/edit.haml
- model_class = Idevice
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/idevices/index.haml
- model_class = Idevice
.page-header
  %h1=t '.title', :default => "iDevices"
= render partial: '/shared/search', locals:{partial: 'idevices', path: idevices_path}
= render '/shared/import', file_name: "iDevices.xlsx", import_path: import_idevices_path

app/views/idevices/index.js.haml
$("#devices").html("<%= escape_javascript(render("idevices")) %>");

app/views/idevices/new.haml
- model_class = Idevice
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/idevices/show.haml
- model_class = Idevice
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:device_type) + ':'
  %br
  = @idevice.device_type
%p
  %strong= model_class.human_attribute_name(:model_number) + ':'
  %br
  = @idevice.model_number
%p
  %strong= model_class.human_attribute_name(:capacity_hd) + ':'
  %br
  = @idevice.capacity_hd
%p
  %strong= model_class.human_attribute_name(:serial_number) + ':'
  %br
  = @idevice.serial_number
%p
  %strong= model_class.human_attribute_name(:asset_tag) + ':'
  %br
  = @idevice.asset_tag
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @idevice.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), idevices_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_idevice_path(@idevice), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), idevice_path(@idevice), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'